### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-self_service#109]
<img width="1282" alt="screen shot 2016-09-01 at 12 31 15 pm" src="https://cloud.githubusercontent.com/assets/6640236/18176998/1e922504-7046-11e6-9f38-c5e7d2245c7a.png">

**My Orders** tab, as you can see is not translated when it should be.  Element has `translate` tab, its just the phrase is absent from the `/client/gettext` folder

Another offender is  **Switch Language:**, again tagged correctly, but not phrase in other languages available in `/gettext`

<img width="1276" alt="screen shot 2016-09-01 at 12 29 28 pm" src="https://cloud.githubusercontent.com/assets/6640236/18177075/74af5bd2-7046-11e6-88db-73c4360bc053.png">

The phrase **Browser Default** should probably also be translated. 

<img width="927" alt="screen shot 2016-09-01 at 1 23 36 pm" src="https://cloud.githubusercontent.com/assets/6640236/18177297/9dffe80c-7047-11e6-874f-08add1312a2a.png">

**Requester** is missing

<img width="924" alt="screen shot 2016-09-01 at 1 27 47 pm" src="https://cloud.githubusercontent.com/assets/6640236/18177383/faf2d4b6-7047-11e6-940c-af32a40ec24b.png">

As is **Order Id** and **Order Date**

<img width="929" alt="screen shot 2016-09-01 at 1 29 10 pm" src="https://cloud.githubusercontent.com/assets/6640236/18177435/35204b96-7048-11e6-884e-076c9597475b.png">

The whole of the shopping cart is missing translation for the following languages: 
* DE-de
* fr
* ja
* ru
* sk
* zh-CN
* zh-Hans-CN

<img width="607" alt="screen shot 2016-09-01 at 4 15 10 pm" src="https://cloud.githubusercontent.com/assets/6640236/18182771/5981b67a-705f-11e6-8543-514caca578f0.png">

Now there IS one translation issue I can't quite track down, it might be https://github.com/patternfly/angular-patternfly but it also might be the SSUI. From the SS below, **Results** is the offender.  First fix I would try would be the same as above (as it too is absent from `/gettext`).

<img width="1112" alt="screen shot 2016-09-01 at 1 44 10 pm" src="https://cloud.githubusercontent.com/assets/6640236/18177952/5c38ba04-704a-11e6-8e53-69966b52ecc9.png">

**Comment by mzazrivec** [comment]
The screenshots above just show the fact that not all strings which are translatable
are translated yet. This is simply a matter of translating the missing string in Zanata
and if you wish to contribute, you are welcome to do so at

https://translate.zanata.org/iteration/view/manageiq-ui-self_service/master?dswid=-1016

The last screenshot shows a Patternfly component (outside of our control), which we currently
have no way of translating.
