### ISSUE TITLE
How to skin the application is not clear

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-ui-self_service#115]
Previously, if someone dropped files into the skin directory, those files would be used for images and text.  Now, I believe the place is assets (even though I search the code and I still see skin)?  I'm a little confused what is the right way to skin the application.

So this is a request for some documentation in the README on how to skin the application, and perhaps a set of tests that validate that if a file is placed in a particular place, then it is actually used (and thus the test serves as an example as well)

**Comment by Fryguy** [comment]
cc @martinpovolny @dclarizio @epwinchell

**Comment by epwinchell** [comment]
cc @himdel

**Comment by himdel** [comment]
OK, so, the skinning still works :)

Except that the devel-mode server serves images from `client/images` and not from `.tmp/images` where the build process puts them :). Still an issue, but doing `gulp build` and loading `localhost:3000/self_service` via Rails does give you the right image..

**Comment by chriskacerguis** [comment]
@himdel Can you please create the docs for this?

**Comment by himdel** [comment]
BTW @chriskacerguis , when I do the docs, I was thinking, maybe it'd be useful for SUI to actually contain a sample theme directory, and maybe even a test that tries to use the theme and validates it applied (although not sure such a test can be done within the realm of our testing framework (all that linking the theme in..), so not promising anything :) ).

What do you think? Would a sample theme make sense in the repo?

**Comment by chriskacerguis** [comment]
@himdel I think that is an AWESOME idea.  I agree with the testing part, however @chalettu is working on setting up some better testing (https://saucelabs.com) so maybe after you get a sample theme, you could work with him with the testing ideas.

**Comment by himdel** [comment]
Hehe, thanks :bow: :) Allright, will do :)

**Comment by serenamarie125** [comment]
what do you mean by theme @himdel ?

I'd imagine that any rebranding that occurs for the Operations UI should be applied to the SSUI as well.  We should discuss this from a UX perspective and make sure that the experience is correct.

**Comment by himdel** [comment]
@serenamarie125 Aah, by theme I mean specifically `skin` - a set of images, additional css files, and js text overrides that can be pulled in to rebrand SSUI..

**Comment by serenamarie125** [comment]
👍 @himdel .  FYI just sent out another email asking PM about requirements per branding as well.  Thanks for the clarification here!

**Comment by himdel** [comment]
Created a [PR with a sample skin](https://github.com/ManageIQ/manageiq-ui-self_service/pull/235) documenting how it works, I'll pick the README to guides too, once merged.

**Comment by epwinchell** [comment]
@himdel Thanks. I'll have a go at it when I have a chance.

**Comment by himdel** [comment]
guides pr https://github.com/ManageIQ/guides/pull/160
