### ISSUE TITLE
Migrate from jshint to eslint

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-self_service#121]
This single issue will encompass all work included in the migration.
Reasons for this change:

1. JSHint team has joined with ESLint
2. Customizability
3. Plugin support (principally https://github.com/Gillespie59/eslint-plugin-angular)
4. ENV support  (amd, jquery, es6)

The sum of tasks to be completed in the fulfillment of this issue (each task encompasses at least one pr, we're going to go slow on this effort, as to avoid any unnecessary messes):
- [x] Add eslint rules and dependencies (extending present state)
- [x] Separate specs from codebase
- [x] Apply eslint changes by rule type across app, a pr for each (large changes) or a few (many small changes) will be made
- [ ] Add eslint task to gulp & travis
- [ ] Remove totality of jshint remnants 

@chriskacerguis feed me (assign) this one, really excited to introduce the ✋ of :goberserk: into our codebase

**Comment by chriskacerguis** [comment]
Assigned!
