### ISSUE TITLE
Required fields not honored when ordering a service

### ISSUE THREAD

**Issue by eclarizio** [ManageIQ/manageiq-ui-self_service#14]
Go to the service catalog, choose a service to order that has a dialog attached to it with required fields. Ensure the required field(s) are not filled out, and observe that the service is still submitted "successfully".

**Comment by chriskacerguis** [comment]
@chalettu - can you take a look at this one?

**Comment by chriskacerguis** [comment]
@AllenBW here you go!

**Comment by eclarizio** [comment]
Tested again for @AllenBW since this is pretty old. Works now, so closing.
