### ISSUE TITLE
Identify and Clean up build tasks

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-self_service#140]
We need to identify and clean up build tasks for this app (minifying, etc).

Each task should be documented

**Comment by chriskacerguis** [comment]
Sending this to @AllenBW since he's pretty much doing it

**Comment by AllenBW** [comment]
oh nice, there's actually some things I want to do with this... a number of tasks we no longer (ever?) use need to be wiped up <3
