### ISSUE TITLE
Switch to node-Sass / libsass

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-self_service#141]
I think it would be good to remove the dependency of ruby-sass and use node-sass?  @himdel @chalettu @AllenBW thoughts on this?

**Comment by himdel** [comment]
I love the idea, that `bundle install` run by `npm` has always been problematic .. and [node-sass](https://github.com/sass/node-sass) seems sufficiently alive :). It does require node 6 however.. we've recently incremented the required version to 6, but the de-facto requirement has really been 4 so far, so.. not sure if before euwe..

**Comment by chriskacerguis** [comment]
@himdel so, it looks like Travis is specifying node 6, and the docs say node 6.  Any thoughts?

**Comment by himdel** [comment]
Just one, node version on the appliance is 0.10.46 :) But, `gulp sass` is ran as part of `gulp build` but whether that is being done on the build host or on the built VM, I'm not sure..

**Comment by chriskacerguis** [comment]
Ok.  I'll talk to the team about getting the appliance updated.  You good with that?

**Comment by himdel** [comment]
Sure, thanks! :)

**Comment by chriskacerguis** [comment]
@AparnaKarve @AllenBW any thoughts / objections to going to Node 6 on the appliance?

**Comment by AllenBW** [comment]
nothing immediate! (reserving the right to eat my words when some super 🐛 rears its head)

**Comment by AparnaKarve** [comment]
Node 6 works! No objections.

**Comment by chriskacerguis** [comment]
@himdel @AllenBW @AparnaKarve @chalettu so, it looks like Node v6 is not available for RHEL yet, but Node v4 is.  Any objections to updating everything to use Node 4 (vs. 6)?  I'll update the docs / tests Monday unless someone strongly disagrees.

**Comment by AparnaKarve** [comment]
@chriskacerguis My local machine uses `node v5.6.0`, which means I (and probably most of us) would have to downgrade it.
Anyway, no objections per se, as long as everything works!

**Comment by chriskacerguis** [comment]
@AparnaKarve yeah, I'm in the same boat.  I just think that it would make most sense for us to test and develop on the same Node version that would be on the appliance.

**Comment by himdel** [comment]
@chriskacerguis please note that node4 means no node-sass .. or only an older version

**Comment by chriskacerguis** [comment]
Yup.  We can run Node 6, it's just the question of the "running AS a Node app" (see https://github.com/ManageIQ/manageiq-ui-self_service/issues/146)

**Comment by himdel** [comment]
Ah, thanks, had not finished reading that one before.. well, if we'll be running node6 on the build machine, then v4 is good enough on the appliance for now :)

**Comment by chriskacerguis** [comment]
@AllenBW all yours dude!
