### ISSUE TITLE
Don't rely on /pictures, use image_href from the API

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-ui-self_service#167]
Right now, for `pictures`, SSUI just assumes that `/pictures/*` will work.

We should instead use the API to get the right url .. `/api/pictures/10000000000010?attributes=image_href` returns an `image_href` which is a full path to that image.

**Comment by dtaylor113** [comment]
Right, currently items on a blueprint's canvas gets their pictures from an API query of service_templates, using the picture.image_href property:

```
{
    "href": "http://localhost:8001/api/service_templates/1000000000011",
    "id": 1000000000011,
    "name": "Dev Workstation",
    "service_type": "composite",
    "picture": {
      "id": 1000000000003,
      "resource_id": 1000000000011,
      "resource_type": "ServiceTemplate",
      "image_href": "http://localhost:8001/pictures/1r3.png"
    },
    "service_template_catalog": {
      "name": "DevOps Team Alpha"
    }
  },
```

**Comment by chriskacerguis** [comment]
@himdel is @dtaylor113 answer sufficient, or do we need to dig deeper?

**Comment by himdel** [comment]
OK, closing, not sure what has changed, but it seems we **are** now getting the full url in `picture.image_href`, and there are no leftover places where we'd hardcode `/pictures/`.

The URL returned by the API will probably change once the API starts supporting actually serving those images, but that shouldn't affect us..
