### ISSUE TITLE
Update Production Build Process to rely soley on ejs

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-self_service#198]
`index.html` presently relies on wiredep for dependency injection when building for production.  This action should be assumed, as it is in dev, by ejs or in this case we would use [gulp-ejs](https://www.npmjs.com/package/gulp-ejs) but not before all other dependencies are updated (to ensure seamless functionality)

**Comment by AllenBW** [comment]
@miq-bot add_label enhancement

**Comment by chriskacerguis** [comment]
@AllenBW can we close this since it is merged?

**Comment by AllenBW** [comment]
@chriskacerguis nope. this is what i was whining about earlier, as soon as we up dependencies i'll switch production to build using ejs rather than wiredep (why wait you ask? because sifting through builds that have the right 💪 and 💃 with the version of node is kinda maddening)

**Comment by chriskacerguis** [comment]
@AllenBW where are we with this?

**Comment by AllenBW** [comment]
Working node-sass presently, will chew on this after 👍

**Comment by AllenBW** [comment]
Been working this today, have not yet hit gold on this, has proved to be more involved than initially thought.  If tomorrow doesn't yield success I'll shelve this for the time being and move on to other priorities.
