### ISSUE TITLE
Add SCSS Lint to repo

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-self_service#215]
Looking to add SCSS Linting to the repo (and associated checks).  Thoughts from the team?

thoughts? @AllenBW @AparnaKarve @serenamarie125 @chalettu @jeff-phillips-18 @dtaylor113 @dgutride @h-kataria 

/cc @chessbyte @Fryguy @dclarizio

**Comment by jeff-phillips-18** [comment]
👍

**Comment by AllenBW** [comment]
Heyo, was just thinking about this, howabout i add https://www.npmjs.com/package/gulp-sass-lint as a gulp task? run along side eslint for all the things? @chriskacerguis

**Comment by chriskacerguis** [comment]
@AllenBW sounds good...let's do it ;)  I'm also going to add it as a CodeClimate engine

**Comment by chalettu** [comment]
I am all for scss linting.

**Comment by chriskacerguis** [comment]
@AllenBW does https://github.com/ManageIQ/manageiq-ui-self_service/pull/229 close this out?

**Comment by AllenBW** [comment]
@chriskacerguis yep!
