### ISSUE TITLE
Minify JS as part of the build process

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-self_service#217]
I think that, as part of the build process, we should start to minify the JS code.  Note: We need to make sure it is compatible with babel (per @himdel)

Thoughts? @martinpovolny @AllenBW @Fryguy 

/cc @dclarizio @chessbyte

**Comment by AllenBW** [comment]
we already min and uglify built js (but not dev js), one of the changes that happened on a commit when updating the dependencies and after the eslint prs made it in(as this enabling this was being held back by a mix of outta date dependencies and absent di for some components)

**Comment by himdel** [comment]
@AllenBW are you sure about that? When I do `gulp build` on current master, and look at the generated `../manageiq/public/self_service/js/app-*.js`, what I see looks like this..

```js
/* eslint angular/window-service: "off" */
// overriden from gettext.config once the initialization is done
if (!window.__) {
  window.__ = function(str) {
    throw new Error([
      'Attempting to call gettext before the service was initialized.',
      'Maybe you\'re calling it in the .config phase? ("' + str + '")',
    ].join(' '));
  };
}

// N_ is OK anywhere
if (!window.N_) {
  window.N_ = function(str) {
    return str;
  };
}
```

So.. yes it's concatenated, but doesn't look minified nor uglified.

In fact, probably an issue.. seems like `/** @ngInject */` doesn't get resolved at all, which needs to be fixed before minifying..

**Comment by martinpovolny** [comment]
What is the gain of minification? Speed? How much speed? Are there any other reasons to do that?

I am quite sure minification will make hunting bugz more challenging so is it worth the speed gain?

**Comment by chriskacerguis** [comment]
@martinpovolny Yes, it would be for speed.  As for "cost vs. benefit", that's good question, and I think that is worth investigating.  As for the hunting bugs, doesn't the Rails Asset pipeline put everything into one big JS file?

**Comment by himdel** [comment]
@chriskacerguis Note that the rails asset pipeline is *not* involved in SSUI, even in production. The result of `gulp build` is served by Apache directly. (That said, yes, the ops UI does minify and uglify.)

**Comment by AllenBW** [comment]
@himdel oh YEAH apologies, I misspoke, odd because uglification is a pipe that the code runs through, so it should be uglified, the fact that the code isn't is mildly concerning... hooray another thing to add on the radar!

**Comment by himdel** [comment]
@AllenBW if it helps, it's commented out in `gulp/tasks/optimize.js`, with a comment to re-enable once the injection problem is resolved :) I'm gonna leave it to you to figure out who added that there 2 weeks ago ;)

**Comment by AllenBW** [comment]
@himdel ?  not commented out on master, and build files aren't uglified, oh the mysteries that we collect on tuesdays...

https://github.com/ManageIQ/manageiq-ui-self_service/blob/master/gulp/tasks/optimize.js#L45

🤔 👍 8️⃣ 🎈

**Comment by himdel** [comment]
Aaah, you already fixed that in  3242e5191aa729d81422a4d5a057c6f4fcdf346e :). However, it still doesn't uglify, weird :)

**Comment by AllenBW** [comment]
dang  you tracked down specific commit... HARDCORE :feelsgood:

**Comment by AllenBW** [comment]
@chriskacerguis you ok if i turn this from discussion into action? need to figure out why we aren't uglifying presently...

**Comment by chriskacerguis** [comment]
@AllenBW got for it.

**Comment by AllenBW** [comment]
@chriskacerguis we can probably close this one
