### ISSUE TITLE
Investigate Gulp Task Pause

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-self_service#224]
As referenced in #216, this issue is to investigate and ameliorate the "pause" that occurs at the end of the following gulp tasks (possibly others):
* gulp test

The "pause" is a break in time between the reporting completion of a task ie `[11:32:07] Finished 'test' after 7.67 s` and the freeing up of the console for additional input..

Curiously, `gulp testonly` does not yield the same pause as test.

@chriskacerguis

**Comment by AllenBW** [comment]
@miq-bot add_label bug

**Comment by chriskacerguis** [comment]
Is this actually causing an issue?

**Comment by dtaylor113** [comment]
I actually did see a pause using `gulp testonly`.  I don't think this has any effect, except that I added a unit test dependency and thought it was causing the pause  -I didn't realize it was a pre-existing condition.

**Comment by AllenBW** [comment]
Not an issue for me :-P

**Comment by chriskacerguis** [comment]
Going to close this for the time being.  Not really seeing this as an issue, if it becomes a problem we can revisit.
