### ISSUE TITLE
Address npm dependency issues found in darga branch

### ISSUE THREAD

**Issue by mtho11** [ManageIQ/manageiq-ui-self_service#59]
<p>bitHound discovered:</p> <ul> <li>4 packages with at least one security vulnerability.</li> <li>5 deprecated packages.</li> <li>31 outdated packages.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/ManageIQ/manageiq-ui-self_service/darga/dependencies/npm">bitHound</a>.</p> 
***
These insecure Dev packages found by Bithound might need to be updated for a product release. Also, there are 31 outdated packages that will only get more outdated.

-- Mike Thompson

**Comment by vanloswang** [comment]
The same issue for me to deploy darga branch with following error:
<pre><code>
# npm install
npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm WARN package.json gulp-minify-html@1.0.6 No repository field.
npm WARN cannot run in wd manageiq-ui-self_service@0.0.1 bower install -F (wd=/root/ws/miq/manageiq-ui-self_service)
npm WARN cannot run in wd manageiq-ui-self_service@0.0.1 gulp build (wd=/root/ws/miq/manageiq-ui-self_service)
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-karma@0.0.4 wants karma@>=0.10 <=0.13
npm ERR! peerinvalid Peer karma-chai@0.1.0 wants karma@>=0.10.9
npm ERR! peerinvalid Peer karma-chai-sinon@0.1.5 wants karma@>=0.6
npm ERR! peerinvalid Peer karma-coverage@0.2.7 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-growl-reporter@0.1.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.10 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-sinon@1.0.5 wants karma@>=0.10

npm ERR! System Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/ws/miq/manageiq-ui-self_service
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/ws/miq/manageiq-ui-self_service/npm-debug.log
npm ERR! not ok code 0
</code></pre>

**Comment by himdel** [comment]
@vanloswang that's definitely not the same issue.. the issue you're having is caused by an old version of `npm` .. do `sudo npm install -g npm` to get a new version of npm and then `npm install` should work..

**Comment by himdel** [comment]
Taking this one, since I'm planning to upgrade `patternfy`, `angular-patternfly` and `angular-bootstrap` anyway...

But, @mtho11 note that we're not actually running any node code in production, it's just for devel setups and tooling..

**Comment by mtho11** [comment]
@himdel np, just wanted to point it out.

**Comment by himdel** [comment]
Sure, better to know about this :) just wanted to make clear that these aren't really security issues..

**Comment by mtho11** [comment]
@himdel I guess the only concern is that downstream developers using the product 6 months from now will most likely not be able to build because of dependency issues. Unless there is an npm shrinkwrap that I missed.

**Comment by himdel** [comment]
There's a small one catching only one problem.. but you're right, we definitely need to keep this up to date..

**Comment by himdel** [comment]
Related so adding here...

```
gulp-minify-css@1.2.4: Please use gulp-clean-css

phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
``

**Comment by chriskacerguis** [comment]
@AllenBW didn't you fix this?

**Comment by AllenBW** [comment]
@chriskacerguis haven't updated package.json yet

**Comment by himdel** [comment]
@AllenBW if you do, feel free to use whatever you can from #72 . But [careful](https://github.com/ManageIQ/manageiq-ui-self_service/pull/72#issuecomment-229726045), upgrading wiredep from 2 to 3 will break the order of external deps in index.html and we really need jquery to go first..

**Comment by chriskacerguis** [comment]
@AllenBW yes, please add your mojo to this

**Comment by chriskacerguis** [comment]
@AllenBW also, take a look here (as @himdel suggested)... https://github.com/ManageIQ/manageiq-ui-self_service/pull/72

**Comment by chriskacerguis** [comment]
@AllenBW This might be a dup of https://github.com/ManageIQ/manageiq-ui-self_service/issues/143

**Comment by AllenBW** [comment]
Mostly a dupe, working it presently, there are 5 or so dependencies that have been depreciated.  Gonna figure if we need these and if so updating them. :metal:
