### ISSUE TITLE
Move resources loading from index.html

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq-ui-self_service#81]
The [client/index.html](https://github.com/ManageIQ/manageiq-ui-self_service/blob/master/client/index.html) file includes every JS file and every package we use in SSUI, and everytime some adds a new JS file or package, it quite often causes conflicts in others PR that are also doing some adding of new resources.

It would be nice to have loading of these resources separated from the `index.html` file, to not force other contributors to rebase their PRs everytime someone adds something new to `index.html`.
I'm not sure what would be the best way to do so though.

If somebody has any idea for this, I can try to do the work once I have nothing more with high priority.

@himdel

**Comment by himdel** [comment]
I think the solution should be to remove the `<link>` and `<script>` tags placed between the `<!-- build... -->` markers from `client/index.html` so that it's always pristine, and make `serve-dev` save the injected & wiredepped file to a different place and serve it from there..

**Comment by chriskacerguis** [comment]
@chalettu - Can you give this a fix?

**Comment by chriskacerguis** [comment]
@AllenBW can you please take a look here.

**Comment by AllenBW** [comment]
🏄
