### ISSUE TITLE
Docker build still fails on Darga

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-ui-self_service#90]
The error I'm getting is the same error as reported on issue #85 , which was closed after the merge of #86.

bower                                 ECMDERR Failed to execute "gulp wiredep", exit code of #8  /opt/manageiq/manageiq-ui-self_service/node_modules/eslint/node_modules/strip-bom/index.js:2 module.exports = x => {                     ^ SyntaxError: Unexpected token >     at Module._compile (module.js:439:25)     at Object.Module._extensions..js (module.js:474:10)     at Module.load (module.js:356:32)     at Function.Module._load (module.js:312:12)     at Module.require (module.js:364:17)     at require (module.js:380:17)     at Object.<anonymous> (/opt/manageiq/manageiq-ui-self_service/node_modules/eslint/lib/config/config-file.js:23:16)     at Module._compile (module.js:456:26)     at Object.Module._extensions..js (module.js:474:10)     at Module.load (module.js:356:32)

Additional error details:
/opt/manageiq/manageiq-ui-self_service/node_modules/eslint/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/manageiq/manageiq-ui-self_service/node_modules/eslint/lib/config/config-file.js:23:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I have check in the ssui pulled into the container and the fix is in (package.jason "plato": "^1.4.0"),
but it still fails.

**Comment by bazulay** [comment]
@Fryguy @himdel 

please advise.

**Comment by himdel** [comment]
> (package.jason "plato": "^1.4.0")

@bazulay if it says `^` and not `~`, the fix is *not* in ;)

**Comment by bazulay** [comment]
@Fryguy @himdel 

getting old ;-)

found the reason for this failure ,
one must delete old images built from darga (before the fix), if we don't it uses the cached later in docker (that contains the SSUI without the fix)
